name: module4_task4
on:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, reopened, edited, ready_for_review]

jobs:
  module3_task0:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        run: |
          cd module4_task4/
          sudo ./setup.sh
      - name: lint
        run: |
          cd module4_task4/
          make lint
      - name: build
        run: |
          cd module4_task4/
          make build
      - name: post
        run: |
          cd module4_task4/
          make POST_TITLE="Test Title" POST_NAME="Test-name" post

      - name: Integration tests
        run: |
          cd module4_task4/
          make integration-tests
          make validate
          make unit-tests
          make package
          make clean

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.0.1
          files: |
            module4_task4/awesome-website.zip
            module4_task4/DEPLOY.md

      - name: archive build
        # If none of previous steps have failed, success returns true
        if: ${{ success()}}
        uses: actions/upload-artifact@v3
        with:
          name: upload-package
          path: module4_task4/awesome-website.zip
