name: module3_task0
on:
  push:
  schedule:
    - cron: "0 3 30 * *"
jobs:
  check_make:
    runs-on: ubuntu-latest
    steps:
      - name: Test make's presence and help
        uses: actions/checkout@v3
        run: |
          cd module3_task0
          make help
